version: '1'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=CUSTOM_HOST
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  import_mongo:
    image: mongo:latest
    restart: always
    container_name: 'import_mongodb'
    ports:
      - 27017:27017

  